name: Update Google Scholar Data

on:
  schedule:
    - cron: '0 12 * * 0'  # Runs daily at 12pm UTC
  workflow_dispatch:

jobs:
  update-scholar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install scholarly

      - name: Run fetch script
        run: python fetch_scholar_data.py

      - name: Commit and push updated data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add public/data/*.json
          git commit -m "Auto-update Google Scholar data"
          git push

